theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:title/
title: Samuel Lee
description: Born in South Korea, lived in Saudi Arabia, UAE, Turkey & USA. 
B.Sc. in Computer Science. 
Golfer. Guitarist.
