theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:title/
title: Samuel Lee
description: Born in South Korea, lived in Saudi Arabia, UAE, Turkey & USA. Studying Computer Science. Previously trained with Special Forces. Golfer. Guitarist. 
logo: "assets/profile.jpg"
